version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    binary: mpkg
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksum.txt

release:
  github:
    owner: sembraniteam
    name: mpkg